// prettier-ignore
export const RoleNames: RoleNameDefinitions = {
    AlphaWolf:    ["Alpha Wolf",    "Alpha Wolf"],
    Apprentice:   ["Apprentice",    "Apprentices"],
    Beholder:     ["Beholder",      "Beholder"],
    BetaWolf:     ["Beta Wolf",     "Beta Wolf"],
    BlackWolf:    ["Black Wolf",    "Black Wolves"],
    Bomber:       ["Bomber",        "Bombers"],
    Bodyguard:    ["Bodyguard",     "Bodyguards"],
    CultLeader:   ["Cult Leader",   "Cult Leaders"],
    Cupid:        ["Cupid",         "Cupid"],
    Cursed:       ["Cursed",        "Cursed"],
    Doppelganger: ["Doppelgänger",  "Doppelgängers"],
    Drunk:        ["Drunk",         "Drunk"],
    FruitBrute:   ["Fruit Brute",   "Fruit Brutes"],
    Ghost:        ["Ghost",         "Ghosts"],
    Idiot:        ["Village Idiot", "Village Idiots"],
    Insomniac:    ["Insomniac",     "Insomniacs"],
    Hunter:       ["Hunter",        "Hunters"],
    Huntress:     ["Huntress",      "Huntresses"],
    LoneWolf:     ["Lone Wolf",     "Lone Wolves"],
    Lycan:        ["Lycan",         "Lycans"],
    Mason:        ["Mason",         "Masons"],
    Mayor:        ["Mayor",         "Mayors"],
    Minion:       ["Minion",        "Minions"],
    Nostradamus:  ["Nostradamus",   "Nostradamus"],
    OldHag:       ["Old Hag",       "Old Hags"],
    Pacifist:     ["Pacifist",      "Pacifists"],
    Priest:       ["Priest",        "Priests"],
    Prince:       ["Prince",        "Princes"],
    Seer:         ["Seer",          "Seers"],
    Sorceress:    ["Sorceress",     "Sorceresses"],
    Spellcaster:  ["Spellcaster",   "Spellcasters"],
    Tanner:       ["Tanner",        "Tanners"],
    ToughGuy:     ["Tough Guy",     "Tough Guys"],
    Troublemaker: ["Troublemaker",  "Troublemakers"],
    Villager:     ["Villager",      "Villagers"],
    Werewolf:     ["Werewolf",      "Werewolves"],
    WildChild:    ["Wild Child",    "Wild Children"],
    Witch:        ["Witch",         "Witches"],
    WolfCub:      ["Wolf Cub",      "Wolf Cubs"],
    Wolfman:      ["Wolfman",       "Wolfmen"],
    Vampire:      ["Vampire",       "Vampires"],
};

export interface RoleNameDefinitions {
    [role: string]: [singular: string, plural: string];
}
